### ISSUE TITLE
공통 Commit / Branch Convention 정의

### ISSUE THREAD

**Issue by hjjam100** [Side-Track/side-track#8]
개인적으로는 
문서 : `doc: [커밋 내용]`
초기 설정 : `init: [커밋 내용]` 
기능 추가 : `feature: [커밋 내용]`
UI 퍼블리싱 : `ui: [커밋내용]`
리팩토링 작업 : `refactor: [커밋내용]`
기타 주석등 기능 영향없는 작업 : `chore: [커밋내용]`

브랜치 명은 `커밋문구/기능명` 이런식으로 하면 될 듯?

**Comment by hjjam100** [comment]
@lunaJYJ chore > etc

**Comment by lunaJYJ** [comment]
생각해보았는데

주석작업은 comm
기타작업은 etc 

로 정리하면 좋을 것 같습니다.

**Comment by hjjam100** [comment]
ㅇㅇ 세분화해도 좋을듯

**Comment by lunaJYJ** [comment]
그럼 저것들 어떻게 사용하는지 용례를 간단하게 써줄 수 있어?

**Comment by hjjam100** [comment]
@lunaJYJ 

```
doc: 기능A 문서화
feature: 게시판 글쓰기 기능 추가
chore: 파일명 변경 
ui: 메인페이지 퍼블리싱
```

한글로 써도 될듯?

브랜치는 풀리퀘 제목으로
feat/board-write 이런식으로

**Comment by hjjam100** [comment]
@lunaJYJ 이거 이제 닫아도 되겠죵?
